name: Create Release

concurrency:
  group: create-release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write


jobs:
  create_release:
    name: "Create Release"

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: afeick/common-github-actions/create_release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
