name: Version Check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_pr_labels:
    name: Verify PR label(s)
    runs-on: ubuntu-latest
    steps:
      - uses: afeick/common-github-actions/version_check@main
        with:
          version_labels: ${{ toJson(github.event.pull_request.labels.*.name) }}
          pr_label_patch: bug fix
